In [ ]:
https://data-flair.training/blogs/data-science-interview-questions-and-answers/

In [13]:
#Q.1 What is a lambda expression in Python?
#Ans. With the help of lambda expression, you can create an anonymous function. Unlike conventional functions, 
#lambda functions occupy a single line of code. The basic syntax of a lambda function is –
#lambda arguments: expression
#An example of lambda function in Python data science is –
x = lambda a : a * 5
print(x(5))

25


In [22]:
#Q.2 How will you measure the Euclidean distance between the two arrays in numpy?
#Ans. In order to measure the Euclidean distance between the two arrays, we will first initialize our two arrays, 
#then we will use the linalg.norm() function provided by the numpy library. Here, numpy is imported as np.

#### Euclidean Distance represents the shortest distance between two points.

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(type(a))

# Solution
e_dist = np.linalg.norm(a-b)
e_dist

<class 'numpy.ndarray'>


11.180339887498949

In [23]:
#Q.3 How will you create an identity matrix using numpy?
#Ans. In order to create the identity matrix with numpy, we will use the identity() function. Numpy is imported as np

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Q.5 How do you create a 1-D array in numpy?
#Ans. You can create a 1-D array in numpy as follows:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [33]:
#Q.6 What function of numpy will you use to find maximum value from each row in a 2D numpy array?
#Ans. In order to find the maximum value from each row in a 2D numpy array, we will use the amax() function as follows –

##############np.amax(input, axis=1)

a = np.arange(4).reshape((2,2))
###print(a)

print(np.amax(a, axis=0))   # Maxima along the first axis
print(np.amax(a, axis=1))   # Maxima along the second axis


[2 3]
[1 3]


In [37]:
#Q.7 Given two lists [1,2,3,4,5] and [6,7,8], you have to merge the list into a single dimension. How will you achieve this?
#Ans. In order to merge the two lists into a single list, we will concatenate the two lists as follows –

#list1 + list2

list1 = [1,2,3,4,5]
list2 = [6,7,8]
list3 = list1 + list2

list3

[1, 2, 3, 4, 5, 6, 7, 8]

In [40]:
#Q.9 How to add a border that is filled with 0s around an existing array?
#Ans. In order to add a border to an array that is filled with 0s, we first make an array Z and initialize it with zeroes. 
#We first import numpy as np.
Z = np.ones((5,5))
Z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
#Then, we perform padding on it with the help of pad() function. 
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [42]:
#Q.10 Consider a (5,6,7) shape array, what is the index (x,y,z) of the 50th element?
#Ans.
print(np.unravel_index(50,(5,6,7)))


(1, 1, 1)


In [46]:
#Q.11 How will you multiply a 4×3 matrix by a 3×2 matrix ?
#Ans. There are two ways to do this. The first method is for the versions of Python that are older than 3.5 –

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
Z = np.dot(np.ones((4,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [50]:
#The second method is for Python version > 3.5,
Z = np.ones((4,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
